"""empty message

Revision ID: a4c11e146ceb
Revises: 
Create Date: 2024-05-06 18:52:03.397195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c11e146ceb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=50), nullable=False),
    sa.Column('client_surname', sa.String(length=50), nullable=False),
    sa.Column('client_business', sa.String(length=50), nullable=False),
    sa.Column('client_email', sa.String(length=150), nullable=False),
    sa.Column('client_phone', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('total_price', sa.BigInteger(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('duties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duty', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('duty')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_table('nationalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nationality')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IATA_code', sa.String(length=3), nullable=False),
    sa.Column('ICAO_code', sa.String(length=6), nullable=False),
    sa.Column('airport_name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('IATA_code'),
    sa.UniqueConstraint('ICAO_code'),
    sa.UniqueConstraint('airport_name')
    )
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('business', sa.Integer(), nullable=False),
    sa.Column('economy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('basic', sa.Integer(), nullable=False),
    sa.Column('main_service', sa.Float(), nullable=False),
    sa.Column('instruction', sa.Float(), nullable=False),
    sa.Column('sec_bonus', sa.Float(), nullable=False),
    sa.Column('per_diem', sa.Float(), nullable=False),
    sa.Column('cleaning_serv', sa.Float(), nullable=False),
    sa.Column('birthday_bonus', sa.Float(), nullable=False),
    sa.Column('additional_bonus', sa.Float(), nullable=False),
    sa.Column('special_project_bonus', sa.Float(), nullable=False),
    sa.Column('bought_days', sa.Float(), nullable=False),
    sa.Column('standby_days', sa.Float(), nullable=False),
    sa.Column('theory_bonus', sa.Float(), nullable=False),
    sa.Column('sick_leave', sa.Float(), nullable=False),
    sa.Column('office_day', sa.Float(), nullable=False),
    sa.Column('office_day_holidays', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crew_id', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('nationality_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('address2', sa.String(length=250), nullable=True),
    sa.Column('address3', sa.String(length=250), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['nationality_id'], ['nationalities.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crew_id')
    )
    op.create_table('fleet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=10), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('assigned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration')
    )
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('base_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('crew', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['fleet.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('IBAN', sa.String(length=35), nullable=False),
    sa.Column('tax_number', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('departure_id', sa.Integer(), nullable=False),
    sa.Column('arrival_id', sa.Integer(), nullable=False),
    sa.Column('departure_UTC', sa.Time(), nullable=False),
    sa.Column('departure_LT', sa.Time(), nullable=False),
    sa.Column('arrival_UTC', sa.Time(), nullable=False),
    sa.Column('arrival_LT', sa.Time(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('cpt_id', sa.Integer(), nullable=False),
    sa.Column('fo_id', sa.Integer(), nullable=False),
    sa.Column('sccm_id', sa.Integer(), nullable=False),
    sa.Column('cc2_id', sa.Integer(), nullable=False),
    sa.Column('cc3_id', sa.Integer(), nullable=False),
    sa.Column('cc4_id', sa.Integer(), nullable=False),
    sa.Column('cc5_id', sa.Integer(), nullable=True),
    sa.Column('cc6_id', sa.Integer(), nullable=True),
    sa.Column('cc7_id', sa.Integer(), nullable=True),
    sa.Column('cc8_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['fleet.id'], ),
    sa.ForeignKeyConstraint(['arrival_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['cc2_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['cc3_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['cc4_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['cc5_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['cc6_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['cc7_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['cc8_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['cpt_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['departure_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['fo_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['sccm_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inflight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(length=10), nullable=False),
    sa.Column('passport', sa.String(length=10), nullable=False),
    sa.Column('pass_expiration', sa.DateTime(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('cert_expiration', sa.DateTime(), nullable=False),
    sa.Column('certificate_id2', sa.Integer(), nullable=True),
    sa.Column('cert_expiration2', sa.DateTime(), nullable=True),
    sa.Column('certificate_id3', sa.Integer(), nullable=True),
    sa.Column('cert_expiration3', sa.DateTime(), nullable=True),
    sa.Column('certificate_id4', sa.Integer(), nullable=True),
    sa.Column('cert_expiration4', sa.DateTime(), nullable=True),
    sa.Column('home_base_id', sa.Integer(), nullable=False),
    sa.Column('roster_assigned', sa.Integer(), nullable=False),
    sa.Column('monthly_BH', sa.Integer(), nullable=False),
    sa.Column('monthly_DH', sa.Integer(), nullable=False),
    sa.Column('yearly_BH', sa.Integer(), nullable=False),
    sa.Column('yearly_DH', sa.Integer(), nullable=False),
    sa.Column('total_BH', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['certificate_id2'], ['models.id'], ),
    sa.ForeignKeyConstraint(['certificate_id3'], ['models.id'], ),
    sa.ForeignKeyConstraint(['certificate_id4'], ['models.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['home_base_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('license'),
    sa.UniqueConstraint('passport')
    )
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('href')
    )
    op.create_table('rosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('base_id', sa.Integer(), nullable=False),
    sa.Column('duty_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('check_in_UTC', sa.Time(), nullable=True),
    sa.Column('check_in_LT', sa.Time(), nullable=True),
    sa.Column('flight1_id', sa.Integer(), nullable=True),
    sa.Column('flight2_id', sa.Integer(), nullable=True),
    sa.Column('flight3_id', sa.Integer(), nullable=True),
    sa.Column('flight4_id', sa.Integer(), nullable=True),
    sa.Column('flight5_id', sa.Integer(), nullable=True),
    sa.Column('flight6_id', sa.Integer(), nullable=True),
    sa.Column('check_out_UTC', sa.Time(), nullable=True),
    sa.Column('check_out_LT', sa.Time(), nullable=True),
    sa.Column('block_hours', sa.Float(), nullable=True),
    sa.Column('duty_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['base_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['duty_id'], ['duties.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['flight1_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['flight2_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['flight3_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['flight4_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['flight5_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['flight6_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rosters')
    op.drop_table('payslips')
    op.drop_table('inflight')
    op.drop_table('flights')
    op.drop_table('bank_details')
    op.drop_table('assignations')
    op.drop_table('prices')
    op.drop_table('hotels')
    op.drop_table('fleet')
    op.drop_table('employees')
    op.drop_table('visibility')
    op.drop_table('states')
    op.drop_table('salary_prices')
    op.drop_table('configurations')
    op.drop_table('airports')
    op.drop_table('roles')
    op.drop_table('projects')
    op.drop_table('nationalities')
    op.drop_table('models')
    op.drop_table('duties')
    op.drop_table('documents')
    op.drop_table('departments')
    op.drop_table('countries')
    op.drop_table('budgets')
    # ### end Alembic commands ###
